#!/bin/bash
#BSUB -P med110
#BSUB -W 1:00
#BSUB -nnodes 1
#BSUB -alloc_flags nvme
#BSUB -J s1
#BSUB -o s1.o%J
#BSUB -e s1.e%J

NNODES=$(cat ${LSB_DJOB_HOSTFILE} | sort | uniq | grep -v login | grep -v batch | wc -l)
source $WORLDWORK/stf011/junqi/covid19/adt_env.sh
export PATH=$(pwd):$PATH

#stage input files to nvme 
DATADIR=/mnt/bb/$USER
jsrun -n${NNODES} -a1 -c1 -r1 cp 3CLPro_protein* ena+db-small.can $DATADIR

jsrun -n${NNODES} -a1 -g1 -c7 -r1 -E DATADIR=$DATADIR smiles_dock_gpu.sh 3CLPro_protein ${DATADIR}/ena+db-small.can  '-10.520,-2.322,-20.631' '54,52,60'

#copy the results back
jsrun -n${NNODES} -a1 -c1 -r1 cp -r $DATADIR/results . 
